package rules.forward
import com.ftn.sbnz.model.models.Machine
import com.ftn.sbnz.model.enums.MachineStatus
import com.ftn.sbnz.model.enums.OperationContext
import com.ftn.sbnz.model.models.IDiagnosticService

global IDiagnosticService backwardService;

rule "PostMaintenance - rising temperature"
no-loop true
when
    // FIX: Only fire if the unit is currently NORMAL
    $m : Machine( status == MachineStatus.NORMAL,
                  context == OperationContext.POST_MAINTENANCE,
                  temperature > 80 && temperature < 90 )
then
    modify($m) {
        setStatus(MachineStatus.SUSPICIOUS),
        addRecommendation("Temperatura raste posle servisa – proveri servisni zahvat.")
    }
    System.out.println("Forward Rule: Post-Maint Heat detected on " + $m.getName());

    // Trigger deep diagnosis
    backwardService.triggerAutomaticDiagnosis($m, "Overheat", 80.0);
end

rule "HighLoad - increased vibration"
no-loop true
when
    $m : Machine( context == OperationContext.HIGH_LOAD, vibration > 8 )
then
    modify($m) {
        setStatus(MachineStatus.CRITICAL),
        addRecommendation("Vibracije pri visokom opterećenju – proveri balans.")
    }
    System.out.println("Povisene vibracije za " + $m.getName() + " u HighLoad kontekstu");
    backwardService.triggerAutomaticDiagnosis($m, "BearingFault", 8.0);
end

rule "Idle - abnormal temperature"
no-loop true
when
    $m : Machine( context == OperationContext.IDLE, temperature > 80 )
then
    modify($m){
        setStatus(MachineStatus.RISKY),
        addRecommendation("Temperatura previsoka u praznom hodu – proveri ventilaciju.")
    }
    System.out.println("Povisenje temperature " + $m.getName() + " u Idle kontekstu");
    backwardService.triggerAutomaticDiagnosis($m, "Overheat", 80.0);
end

// --- If vibration normalizes ---
rule "Normal vibration range - post maintenance"
no-loop true
when
    $m : Machine( context == OperationContext.POST_MAINTENANCE, vibration <= 7, temperature <= 80, currentPercentOfRated <= 100 , status != MachineStatus.NORMAL )
then
    modify($m){
        setStatus(MachineStatus.NORMAL),
        resetRecommendations()
    }
    System.out.println("Rule fired: PostMaintenance normalization → " + $m.getName());
end
