package rules.forward
import com.ftn.sbnz.model.models.Machine
import com.ftn.sbnz.model.enums.MachineStatus
import com.ftn.sbnz.model.enums.OperationContext
import com.ftn.sbnz.model.models.IDiagnosticService // Import the interface

global IDiagnosticService backwardService; // Use the interface type

// --- Moderate overheat ---
rule "Temperature > 85°C (Risky)"
no-loop true
when
    $m : Machine( temperature > 85 && temperature <= 90,
                  status not in ( MachineStatus.RISKY, MachineStatus.CRITICAL),
                  context not in (OperationContext.IDLE, OperationContext.POST_MAINTENANCE) )
then
    modify($m) {
        setStatus(MachineStatus.RISKY),
        addRecommendation("Proveri hlađenje – temperatura iznad praga za normalni režim.")
    }
    System.out.println("Forward Rule: Moderate heat detected on " + $m.getName());

    // TRIGGER DIAGNOSIS: Call the backward chaining service
    backwardService.triggerAutomaticDiagnosis($m, "Overheat", 85.0);
end

// --- Critical temperature under high load ---
rule "Temperature > 90°C (Critical)"
no-loop true
when
    $m : Machine( temperature > 90, status != MachineStatus.CRITICAL )
then
    modify($m) {
        setStatus(MachineStatus.CRITICAL),
        addRecommendation("Kritično pregrevanje! Razmotri gašenje mašine.")
    }
    System.out.println("Forward Rule: Critical heat detected on " + $m.getName());

//    // TRIGGER DIAGNOSIS: Call the backward chaining service
//    backwardService.runBackwardChainingForOne($m.getId(), "Overheat");
    backwardService.triggerAutomaticDiagnosis($m, "Overheat", 90.0);
end