package rules.forward
import com.ftn.sbnz.model.models.Machine
import com.ftn.sbnz.model.enums.MachineStatus
import com.ftn.sbnz.model.enums.OperationContext
import com.ftn.sbnz.model.models.IDiagnosticService

global IDiagnosticService backwardService;

// --- Vibration above normal threshold ---
rule "Vibration slightly high (Risky)"
no-loop true
when
    $m : Machine( vibration > 7.1 && vibration <= 10, status in (MachineStatus.NORMAL, MachineStatus.SUSPICIOUS), context != OperationContext.HIGH_LOAD )
then
    modify($m) {
        setStatus(MachineStatus.RISKY),
        addRecommendation("Proveri balans rotora – blago povećane vibracije.")
    }
    System.out.println("Rule fired: Slightly high vibration → Suspicious for " + $m.getName());
    // Tringgering imbalance diagnostics
    backwardService.triggerAutomaticDiagnosis($m, "Imbalance", 7.1);
end

// --- Very high vibration ---
rule "Vibration very high (Critical)"
no-loop true
when
    $m : Machine( vibration > 10, status != MachineStatus.CRITICAL, context != OperationContext.HIGH_LOAD )
then
    modify($m) {
        setStatus(MachineStatus.CRITICAL),
        addRecommendation("Jako povećane vibracije – proveri balans i ležajeve.")
    }
    System.out.println("Rule fired: High vibration → Risky for " + $m.getName());
    // Triggering bearing fault diagnostics
    // Maybe change to Bearing Load
    backwardService.triggerAutomaticDiagnosis($m, "Imbalance", 10.0);
end